### ISSUE TITLE
Update Python module "google" to version 2.0.1

### ISSUE THREAD

**Issue by constantin-evseev** [opsdisk/pagodo#11]
Module named "google" not found in Python 3.6.4 on MS Windows. His new name is "googlesearch". After manual fixing all working fine.

**Comment by opsdisk** [comment]
Thanks for the heads up @constantin-evseev I noticed he updated the library a week or so ago.  Give me a few days to take a look and update any code/notes with this repo.

**Comment by opsdisk** [comment]
Nice catch...found his commit here: https://github.com/MarioVilas/googlesearch/commit/92309f4f23a6334a83c045f7c51f87b904e7d61d

Just updated scripts and requirements.txt file to reflect.
