### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by littleheary** [opsdisk/pagodo#25]
root@ubuntu:/soft/dork-tools/pagodo# python3 ghdb_scraper.py 
  File "ghdb_scraper.py", line 33
    print(f"[-] Error retrieving google dorks from: {url}")
                                                         ^
SyntaxError: invalid syntax
root@ubuntu:/soft/dork-tools/pagodo# 
root@ubuntu:/soft/dork-tools/pagodo# ls
ghdb_scraper.py                   google_dorks.json  pagodo.py  requirements.txt
google_dorks_20181229_113249.txt  LICENSE            README.md  user_agents.txt
root@ubuntu:/soft/dork-tools/pagodo# python3 pagodo.py 
  File "pagodo.py", line 32
    self.log_file = f"pagodo_results_{get_timestamp()}.txt"
                                                          ^
SyntaxError: invalid syntax
root@ubuntu:/soft/dork-tools/pagodo# python pagodo.py 
  File "pagodo.py", line 32
    self.log_file = f"pagodo_results_{get_timestamp()}.txt"
                                                          ^
SyntaxError: invalid syntax

**Comment by opsdisk** [comment]
Hi @littleheary - thanks for submitting an issue.  Can you run `python -V` and tell me what version of Python is running?  I'm guessing you have a version less than 3.6.  Version 3.6+ is required.

**Comment by opsdisk** [comment]
Going to close this one out.  Let me know if you have any other issues/questions.
