### ISSUE TITLE
Console interface

### ISSUE THREAD

**Issue by saeeddhqan** [opsdisk/pagodo#26]
Hi dear,
you can use Maryam for the user interface. If you use Maryam, your program will a framework like Metasploit.
If you wanted, please ask how to work.
[http://github.com/saeeddhqan/maryam](https://github.com/saeeddhqan/maryam)

**Comment by opsdisk** [comment]
HI @saeeddhqan - thanks for letting me know about your project.  However, at this time, I'd rather keep pagodo simple without any framework overhead.  Feel free to incorporate it into maryam though.
