### ISSUE TITLE
Tool is not working

### ISSUE THREAD

**Issue by crazywifi** [opsdisk/pagodo#50]
[-] Error with dork: intitle:"Ganglia" "Cluster Report for"
[-] EXCEPTION: module 'googlesearch' has no attribute 'search'
Traceback (most recent call last):
  File "/root/bugbounty/pagodo/pagodo.py", line 103, in go
    for url in googlesearch.search(
AttributeError: module 'googlesearch' has no attribute 'search'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bugbounty/pagodo/pagodo.py", line 227, in <module>
    pgd.go()
  File "/root/bugbounty/pagodo/pagodo.py", line 145, in go
    if e.code == 429:
AttributeError: 'AttributeError' object has no attribute 'code'

**Comment by opsdisk** [comment]
Hi @crazywifi  - thanks for submitting the issue.

How did you install it?  As a reference, the instructions are here: https://github.com/opsdisk/pagodo#installation

I'd recommend creating a Python virtual environment.  My guess is you're using a system-wide install of the `googlesearch` library that is outdated.

**Comment by crazywifi** [comment]
Thanks, it's working now.
