### ISSUE TITLE
[!] Specify a valid file containing Google dorks with -g

### ISSUE THREAD

**Issue by spaceh3ad** [opsdisk/pagodo#54]
I got error when execute code drom Hak5 tutrial.

`(.venv) josh@josh-pc:~/pagodo$ python3 pagodo.py -d amazon.com -g "dorks/files_containig_juicy_info.dorks"  -l 50 -s -e 35.0 -j 1.1
`

`[!] Specify a valid file containing Google dorks with -g #54
`

**Comment by opsdisk** [comment]
Hi @spaceh3ad - looks like "containing" is spelled incorrectly.  Try this:

```bash
python3 pagodo.py -d amazon.com -g "dorks/files_containing_juicy_info.dorks" -l 50 -s -e 35.0 -j 1.1 
```

**Comment by opsdisk** [comment]
Closing this one out @spaceh3ad - let me know if it's still not working correctly.
