### ISSUE TITLE
details

### ISSUE THREAD

**Issue by bradfodley** [opsdisk/pagodo#56]
where does details found saved?

**Comment by opsdisk** [comment]
Hi @bradfodley

Could you specify which script you're running?  `ghdb_scraper.py` or `pagodo.py`?

What specific details are you looking for?

**Comment by bradfodley** [comment]
after running python3 pagodo.py -d example.com -g dorks.txt -l 50 -s -e 35.0 -j 1.1, where will the details found be saved and also can i add more than domain for the search?

**Comment by opsdisk** [comment]
Hi @bradfodley 

To your first question, with the `-s` switch specified, it will "Save the html links to pagodo_results_\<TIMESTAMP\>.txt file."

Can you clarify what "add more than domain" means.  Are you looking to specify more than 1 domain, so something like `-d example.com,apple.com`?  If so, that's not supported.

If you're looking to add your own custom Google dorks, you can add those to the file specified with `-g`

The actual Google search query is created here: https://github.com/opsdisk/pagodo/blob/master/pagodo.py#L74

```python
if self.domain:
    # site: must be at the beginning of the query.
    query = f"site:{self.domain} {dork}"
else:
    query = dork
```

**Comment by opsdisk** [comment]
Closing this one out.
