### ISSUE TITLE
traceback problem

### ISSUE THREAD

**Issue by QoQoQ1** [opsdisk/pagodo#66]
hi, when im trying executing the command , this problem pop up

Traceback (most recent call last):
  File "pagodo.py", line 15, in <module>
    import yagooglesearch
ModuleNotFoundError: No module named 'yagooglesearch'

please help,
thanks :>

**Comment by opsdisk** [comment]
Hi @QoQoQ1 - Looks like you need to install the `yagooglesearch` library.  See https://github.com/opsdisk/pagodo#installation

**Comment by opsdisk** [comment]
Going to close this one out.  Let me know if the solution above doesn't work.
