### ISSUE TITLE
Some parameters doesn't work

### ISSUE THREAD

**Issue by sibercan** [opsdisk/pagodo#72]
![parameters](https://user-images.githubusercontent.com/72570309/194756346-78aa9ea7-cbf4-4fc7-98ce-f01b12cd753c.png)
Hi,

While the script is running, it does not use some parameter values (-i, -x, -m) that I gave at the beginning. Instead, it uses some default values in the code. I tried to manually change the code myself but it kept working with default settings every time.

Regards..

**Comment by opsdisk** [comment]
Thanks for submitting an issue @sibercan - it's a bit confusing.  The `-i` and `-x` switches control the sleep time between different Google dork searches.  It looks like your dorks.txt only contained 1 search term.  If your dorks.txt file had contained multiple searches, you would have seen the sleep time controlled by the above switches.

What you're seeing is the sleep time between page results for the **same** Google dork search.  So if your search term had multiple pages of results, the 12 seconds is the delay between clicking "Next" if you were using the GUI.  It's part of the `yagooglesearch` library being used - https://github.com/opsdisk/yagooglesearch/blob/master/yagooglesearch/__init__.py#L575

I'll keep the issue open if you have any other questions.

**Comment by sibercan** [comment]
Thank you very much for the detailed explanation.
As you said, there is only 1 entry in my 'dorks.txt' file.
In this case I can use `yagooglesearch` library with different parameters to change the wait time between pages.

Regards
