### ISSUE TITLE
unicode decode error

### ISSUE THREAD

**Issue by jor101** [opsdisk/pagodo#81]
![Screenshot (8)](https://user-images.githubusercontent.com/123481908/215855641-83ab229f-bfdc-4c90-951b-5df3ba910cc1.png)

**Comment by opsdisk** [comment]
Hi @jor101 - It appears to not like your `dorks.txt` file.  Can you run these commands and provide me the `output.txt` file?

```bash
ls -la dorks.txt > output.txt
cat dorks.txt >> output.txt
file dorks.txt >> output.txt
xxd dorks.txt >> output.txt
```

**Comment by jor101** [comment]
thank you so much for looking into my issue. fortunately i have solved this error on my own by changing utf-8 to  latin1 encoding. everything else is going fine.  very effective script . hope in future you might consider adding more search engine like bing , ask duck etc. peace !!
