### ISSUE TITLE
Python 3.11.2   line 125   SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by soulkkkkk** [opsdisk/pagodo#82]
File ".\pagodo.py", line 125
    self.base_file_name = f'pagodo_results_{datetime.datetime.now().strftime("%Y%m%d_%H%M%S")}'
                                                                                              ^
SyntaxError: invalid syntax

**Comment by opsdisk** [comment]
Hi @soulkkkkk - thanks for submitting the issue.  Can you provide me the Operating System and the output of `python -V` before you run the command?  I just want to make sure you're actually running Python 3.11 (hopefully in a virtual environment) and not the system/OS-level Python, which may be Python 2.x

**Comment by soulkkkkk** [comment]
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
I will not set up a virtual environment, I just install normal python3 on win10

**Comment by opsdisk** [comment]
What is the entire command you are running?

**Comment by Bongo10** [comment]
Pagodo dorking  on international spanish written  websites seems not been working.  Anything that should be done on my part in order to make work? Thanks

**Comment by opsdisk** [comment]
Hi @Bongo10 Can you provide me the Operating System and the output of `python -V` before you run the command? 

Can you also provide the full command and any screenshots?

**Comment by opsdisk** [comment]
You still running into this issue @soulkkkkk / @Bongo10 ?

**Comment by opsdisk** [comment]
Closing out this issue @soulkkkkk / @Bongo10
