### ISSUE TITLE
SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:992)')))

### ISSUE THREAD

**Issue by beachf2lightning** [opsdisk/pagodo#84]
Hello, I'd appreciate your feedback on the SSLError I'm getting.
A search indicates a Python problem, but I'm not certain.

The  error code  is SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:992)')))

See the attached file  "pagodo_python_error.txt"  for details.

[pagodo_python_error.txt](https://github.com/opsdisk/pagodo/files/11372567/pagodo_python_error.txt)

**Comment by opsdisk** [comment]
Hi @beachf2lightning - What type of proxy are you using?  I see a mention of an sshd service in the references section.  If you're trying to proxy it through an SSH SOCKS proxy, you'll need to use `-p socks5h://127.0.0.1:9030,socks5h://127.0.0.1:9025`

**Comment by beachf2lightning** [comment]
Hi, 
In answer to your question -->for a proxy I am using a droplet on digital ocean
 Ubuntu 22.10 (GNU/Linux 5.19.0-41-generic x86_64)

After your comment about proxies, I changed my commands etc. to incorporate socks5h

See the attached file  "pagodo_python_errorTwo.txt" for details
[pagodo_python_errorTwo.txt](https://github.com/opsdisk/pagodo/files/11379059/pagodo_python_errorTwo.txt)

**Comment by beachf2lightning** [comment]
I progressed - no longer have error code
I used the following https://github.com/opsdisk/pagodo/discussions/71?sort=top
I will follow through on my testing and get back to you if I need assistance.
Thanks for your time
